# Bibliotecas

## Sistema (os, makedirs, glob)

In [1]:
from os import makedirs
import os
import glob

## Básicos (numpy, math, display, locale, time, random, re)

In [2]:
# !python -m pip install jupyter


# !python -m pip install IPython
from IPython.display import display

import math

# !python -m pip install numpy
import numpy as np

import locale
# locale.setlocale(locale.LC_ALL, "pt_BR.UTF-8")  # Use "" for auto, or force e.g. to "en_US.UTF-8"

import time
from datetime import datetime, timedelta, date

from pandas.tseries.offsets import BDay # para os dias úteis
# today = datetime.datetime.today()
# print(today - BDay(4)) # 4 dias úteis atrás

# # !python -m pip install random
import random
random.seed(42)

# !python -m pip install regex
import re

## Leitura e análise de dados (Excel, Pandas, Spark)

In [3]:
# !python -m pip install findspark

# !python -m pip install openpyxl
# import openpyxl

# !python -m pip install xlsxwriter
# import xlsxwriter

# !python -m pip install xlrd
# import xlrd

# !python -m pip install python-calamine
# import python_calamine


# !python -m pip install pandas
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
# pd.set_option('display.float_format', lambda x: '%.2f' % x)

# Ler arquivo

## Lista de Ações Tratada

In [11]:
var_caminho_pasta = r"C:\Users\ricardopeloi\OneDrive - falconi365\Data Science\O_Mais_Novo_Day_Trader_do_Brasil\o_mais_novo_day_trader_do_brasil\Bases"
var_arquivo_lista_acoes_tratada = r"\Lista de ações Tratada.xlsx"

bd_arquivo_original = pd.read_excel(var_caminho_pasta + var_arquivo_lista_acoes_tratada)

bd_arquivo_original.sort_values([col for col in bd_arquivo_original if col.startswith("Volume no último dia útil")], ascending = False).head(5)

,Ticker,Nome da Empresa,Volume no último dia útil (lido em 10/03/2025),Market Cap
0,HAPV3,Hapvida,97225000,15210568704
1,B3SA3,B3,41638200,54814535680
2,MGLU3,Magazine Luiza,40884800,6073303552
3,COGN3,Cogna,36134200,3024730624
4,ABEV3,Ambev,30190400,205837058048

In [12]:
# var_caminho_pasta = r"C:\Users\ricardopeloi\OneDrive - falconi365\Data Science\O_Mais_Novo_Day_Trader_do_Brasil\o_mais_novo_day_trader_do_brasil\Bases"
var_arquivo_lista_acoes_analise = r"\Lista de ações Análise 2025-03-10.xlsx"

bd_acoes_analise = pd.read_excel(var_caminho_pasta + var_arquivo_lista_acoes_analise)

bd_acoes_analise.head(5)

,Ticker,Nome da Empresa,Volume no último dia útil (lido em 10/03/2025),Market Cap,Alfa (15 dias),Preço Close há 15 dias,Preço HLC em 10/03/2025,Preço HLC há 15 dias,Alfa (39 dias),Preço Close há 39 dias,Preço HLC há 39 dias,Datas dos martelos
0,HAPV3,Hapvida,97225000,15210568704,-0.04,2.51,2.08,2.45,-0.01,2.45,2.39,"21/01/25, 24/01/25, 10/02/25, 13/02/25, 17/02/..."
1,B3SA3,B3,41638200,54814535680,-0.09,11.59,10.48,11.50,-0.02,11.09,10.94,"13/01/25, 21/01/25, 24/01/25, 28/01/25, 03/02/..."
2,MGLU3,Magazine Luiza,40884800,6073303552,-0.00,7.38,8.13,7.31,0.01,7.27,7.13,"24/01/25, 04/02/25, 11/02/25, 12/02/25, 27/02/..."
3,COGN3,Cogna,36134200,3024730624,-0.01,1.70,1.66,1.67,0.01,1.39,1.38,"14/01/25, 16/01/25, 22/01/25, 29/01/25, 03/02/..."
4,ABEV3,Ambev,30190400,205837058048,0.17,11.13,13.12,11.11,0.08,11.11,11.07,"14/01/25, 20/01/25, 23/01/25, 07/02/25, 10/02/..."