# Bibliotecas

## Sistema (os, makedirs, glob)

In [9]:
from os import makedirs
import os
import glob
from os import listdir

import dotenv
def load_dotenv():
    """Load the .env file normally and also from the current directory."""
    dotenv.load_dotenv()
    dotenv.load_dotenv(dotenv.find_dotenv(usecwd=True))

load_dotenv()
var_caminho = os.environ.get('var_caminho_fonte')

## Básicos (numpy, math, display, locale, time, random, re)

In [2]:
# !python -m pip install jupyter


# !python -m pip install IPython
from IPython.display import display

import math

# !python -m pip install numpy
import numpy as np

import locale
# locale.setlocale(locale.LC_ALL, "pt_BR.UTF-8")  # Use "" for auto, or force e.g. to "en_US.UTF-8"

import time
from datetime import datetime, timedelta, date

from pandas.tseries.offsets import BDay # para os dias úteis
# today = datetime.datetime.today()
# print(today - BDay(4)) # 4 dias úteis atrás

# # !python -m pip install random
import random
random.seed(42)

# !python -m pip install regex
import re

## Leitura e análise de dados (Excel, Pandas, Spark)

In [3]:
# !python -m pip install findspark

# !python -m pip install openpyxl
# import openpyxl

# !python -m pip install xlsxwriter
# import xlsxwriter

# !python -m pip install xlrd
# import xlrd

# !python -m pip install python-calamine
# import python_calamine


# !python -m pip install pandas
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
# pd.set_option('display.float_format', lambda x: '%.2f' % x)

## Finanças (yfinance, mplfinance)

In [4]:
# https://pypi.org/project/yfinance/
# https://github.com/ranaroussi/yfinance/wiki/Ticker

!python -m pip install yfinance
import yfinance as yf

!python -m pip install mplfinance
import mplfinance as mpf

# # Em R
# # https://cran.r-project.org/web/packages/BatchGetSymbols/index.html

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: yfinance in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (0.2.54)
Requirement already satisfied: pandas>=1.3.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: requests>=2.31 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (4.3.6)
Requirement already satisfied: pytz>=2022.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2025.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (3.17.9)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from yfinance) (4.13.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from pandas>=1.3.0->yfinance) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from requests>=2.31->yfinance) (2025.1.31)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mplfinance in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (0.12.10b0)
Requirement already satisfied: matplotlib in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from mplfinance) (3.10.1)
Requirement already satisfied: pandas in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from mplfinance) (2.2.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (2.2.3)
Requirement already satisfied: packaging>=20.0 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from matplotlib->mplfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib->mplfinance) (1.17.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from pandas->mplfinance) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ricardopeloi\appdata\roaming\python\python313\site-packages (from pandas->mplfinance) (2025.1)

## Visualização (matplotlib, seaborn, plotly)

In [5]:
# !python -m pip install matplotlib
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib import ticker
from matplotlib.ticker import FormatStrFormatter, StrMethodFormatter

# !python -m pip install seaborn
import seaborn as sns

# !python -m pip install plotly
# import plotly.graph_objects as go
# import plotly.express as px
# from plotly.subplots import make_subplots

# !python -m pip install graphviz
# import graphviz

# Funções

# Leitura dos dados

In [34]:
bd_recomendacoes_original = pd.read_excel(var_caminho + r"\Recomendações\Top 5 todas as análises.xlsx")
bd_recomendacoes_original

,index,Ticker,Nome da Empresa,Volume no último dia útil,Alfa (15 dias),Preço Close há 15 dias,Preço HLC,Preço HLC há 15 dias,Alfa (39 dias),Preço Close há 39 dias,Preço HLC há 39 dias,Datas dos martelos,Data análise
0,0,EMBR3,Embraer,6795700,0.59,26.84,33.40,26.80,0.45,22.50,22.52,"15/02/24, 23/02/24, 06/03/24, 11/03/24, 18/03/...",2024-03-30
1,1,SUZB3,Suzano,4548700,0.37,59.15,63.78,58.79,0.33,55.27,54.55,"02/02/24, 07/02/24, 15/02/24, 19/02/24, 05/03/...",2024-03-30
2,2,ORVR3,Orizon,544500,0.03,37.95,37.69,37.98,0.28,33.35,33.36,"16/02/24, 04/03/24, 11/03/24, 19/03/24, 21/03/...",2024-03-30
3,3,BRKM5,Braskem,4610300,0.59,20.15,26.66,20.28,0.26,19.37,19.53,"01/02/24, 05/02/24, 08/02/24, 08/03/24, 12/03/24",2024-03-30
4,4,ENAT3,Enauta,1483800,0.21,25.15,29.33,25.56,0.21,23.10,23.01,"02/02/24, 19/02/24, 06/03/24, 13/03/24, 26/03/24",2024-03-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,SBSP3,Sabesp,3977900,0.92,105.00,114.39,104.25,0.44,94.16,94.36,"2025-03-12, 2025-03-14, 2025-03-31, 2025-04-02...",2025-04-25
96,1,JBSS3,JBS,13236100,0.51,41.59,46.67,41.81,0.41,30.73,30.78,"2025-03-14, 2025-04-04, 2025-04-15, 2025-04-17,",2025-04-25
97,2,RENT3,Localiza,7810300,0.44,37.40,41.28,37.10,0.36,27.95,27.96,"2025-03-06, 2025-03-10, 2025-03-27, 2025-03-28...",2025-04-25
98,3,UNIP6,Unipar,142800,-0.12,54.56,54.60,54.74,0.28,45.09,45.02,"2025-03-10, 2025-03-25, 2025-04-07, 2025-04-14...",2025-04-25
99,4,AMBP3,Ambipar,97200,1.86,126.43,144.58,127.05,0.25,127.50,130.70,"2025-03-05, 2025-03-06, 2025-03-13, 2025-03-18...",2025-04-25

# Análises

## Verificar ações que mais apareceram: elas cresceram?

In [70]:
bd_recomendacoes_analise_1 = bd_recomendacoes_original.copy()

var_top_5_recomendacoes = bd_recomendacoes_analise_1.groupby("Nome da Empresa").count()[["Ticker"]].sort_values("Ticker", ascending = False).head().index.to_list()
var_top_5_recomendacoes_ticker = bd_recomendacoes_analise_1.groupby(["Nome da Empresa", "Ticker"]).count()[["index"]].sort_values("index", ascending = False).head()#.index.to_list()

# var_top_5_recomendacoes
var_top_5_recomendacoes_ticker = var_top_5_recomendacoes_ticker.reset_index()["Ticker"].to_list()
var_top_5_recomendacoes_ticker

['EMBR3', 'UNIP6', 'JBSS3', 'SBSP3', 'RENT3']

In [78]:
# for recomendacao in var_top_5_recomendacoes:
for recomendacao in var_top_5_recomendacoes_ticker:
    # print(recomendacao)
    

    # bd_recomencao = bd_recomendacoes_analise_1.set_index("Ticker").loc[recomendacao].set_index("Data análise")[["Preço HLC"]].copy()
    bd_recomencao = bd_recomendacoes_analise_1.set_index("Ticker").loc[recomendacao].set_index("Data análise")[["Preço HLC"]].copy()
    # display(bd_recomencao)
    
    var_variacao_dias = (bd_recomencao.index.to_list()[-1] - bd_recomencao.index.to_list()[0]).days
    # display(var_variacao_dias)

    var_variacao_valor = bd_recomencao["Preço HLC"].iloc[-1]/bd_recomencao["Preço HLC"].iloc[0] - 1


    # print(recomendacao + " (" + bd_recomendacoes_analise_1[bd_recomendacoes_analise_1["Nome da Empresa"] == recomendacao].iloc[0].loc["Ticker"] + "): " + "{:.0%}".format(var_variacao_valor))
    print(recomendacao + " (" + bd_recomendacoes_analise_1[bd_recomendacoes_analise_1["Ticker"] == recomendacao].iloc[0].loc["Ticker"] + "): " + "{:.0%}".format(var_variacao_valor) + ", ou " + "{:.0%}".format(var_variacao_valor/(var_variacao_dias/365)) + " a.a")

    display(bd_recomencao)

EMBR3 (EMBR3): 90%, ou 88% a.a

              Preço HLC
Data análise
2024-03-30        33.40
2024-04-14        31.98
2024-06-15        38.01
2025-01-18        59.99
2025-01-20        60.09
2025-03-10        74.00
2025-03-15        74.90
2025-04-01        64.86
2025-04-02        65.27
2025-04-03        64.87
2025-04-04        63.36

UNIP6 (UNIP6): -1%, ou -16% a.a

              Preço HLC
Data análise
2025-04-01        55.17
2025-04-02        56.16
2025-04-03        19.23
2025-04-04        19.17
2025-04-12        54.74
2025-04-15        54.30
2025-04-17        53.59
2025-04-19        53.26
2025-04-24        54.30
2025-04-25        54.60

JBSS3 (JBSS3): 63%, ou 73% a.a

              Preço HLC
Data análise
2024-06-15        28.70
2025-04-01        41.12
2025-04-02        41.57
2025-04-04        13.69
2025-04-12        41.45
2025-04-15        43.09
2025-04-17        43.53
2025-04-19        43.51
2025-04-24        46.98
2025-04-25        46.67

SBSP3 (SBSP3): 41%, ou 40% a.a

              Preço HLC
Data análise
2024-04-14        81.17
2025-04-12       106.58
2025-04-15       108.02
2025-04-17       107.33
2025-04-19       108.32
2025-04-24       111.90
2025-04-25       114.39

RENT3 (RENT3): 7%, ou 208% a.a

              Preço HLC
Data análise
2025-04-12        38.43
2025-04-15        39.29
2025-04-17        38.95
2025-04-19        39.62
2025-04-24        40.20
2025-04-25        41.28

Das 5 ações mais recomendadas, 3 cresceram de 40% a 90% em 1 ano. Teriam sido grandes investimentos.

Já as outras duas ações ficaram no zero a zero, caso o jogador saia no momento certo. São ações bem voláteis, flexionando preço fortemente ao longo dos períodos e podendo gerar perdas potenciais maiores

## Colocando 1000 em cada uma na primeira recomendação até período mais recente

In [79]:
bd_dados_historico = pd.read_excel(var_caminho + r"\Bases\Base de Dados Histórico.xlsx")
bd_dados_historico_top_recomendacoes = bd_dados_historico[
    (bd_dados_historico["Date"] == max(bd_dados_historico["Date"]))
    *
    (bd_dados_historico["Ticker"].isin(var_top_5_recomendacoes_ticker))
][["Ticker", "Date", "HLC"]]

bd_dados_historico_top_recomendacoes

     Ticker       Date    HLC
8916  RENT3 2025-04-25  42.45
8928  JBSS3 2025-04-25  47.51
8968  SBSP3 2025-04-25 115.20
8971  EMBR3 2025-04-25  63.35
9262  UNIP6 2025-04-25  54.45

In [87]:
var_data_maxima = max(bd_dados_historico_top_recomendacoes["Date"])

# for recomendacao in var_top_5_recomendacoes:
for recomendacao in var_top_5_recomendacoes_ticker:
    print(recomendacao)
    

    # bd_recomencao = bd_recomendacoes_analise_1.set_index("Ticker").loc[recomendacao].set_index("Data análise")[["Preço HLC"]].copy()
    bd_recomencao = bd_recomendacoes_analise_1.set_index("Ticker").loc[recomendacao].set_index("Data análise")[["Preço HLC"]].copy()
    # display(bd_recomencao)
    
    var_variacao_dias = (var_data_maxima - bd_recomencao.index.to_list()[0]).days
    # display(var_variacao_dias)

    var_variacao_valor = bd_dados_historico_top_recomendacoes.set_index("Ticker").loc[recomendacao, "HLC"]/bd_recomencao["Preço HLC"].iloc[0] - 1
    print("Preço inicial: " + "{:.2f}".format(bd_recomencao["Preço HLC"].iloc[0]))
    print("Preço final: " + "{:.2f}".format(bd_dados_historico_top_recomendacoes.set_index("Ticker").loc[recomendacao, "HLC"]))


    # print(recomendacao + " (" + bd_recomendacoes_analise_1[bd_recomendacoes_analise_1["Nome da Empresa"] == recomendacao].iloc[0].loc["Ticker"] + "): " + "{:.0%}".format(var_variacao_valor))
    print("Crescimento: " + "{:.0%}".format(var_variacao_valor) + ", ou " + "{:.0%}".format(var_variacao_valor/(var_variacao_dias/365)) + " a.a")

    # display(bd_recomencao)
    print()

EMBR3
Preço inicial: 33.40
Preço final: 63.35
Crescimento: 90%, ou 84% a.a

UNIP6
Preço inicial: 55.17
Preço final: 54.45
Crescimento: -1%, ou -20% a.a

JBSS3
Preço inicial: 28.70
Preço final: 47.51
Crescimento: 66%, ou 76% a.a

SBSP3
Preço inicial: 81.17
Preço final: 115.20
Crescimento: 42%, ou 41% a.a

RENT3
Preço inicial: 38.43
Preço final: 42.45
Crescimento: 10%, ou 293% a.a