# Bibliotecas

## Sistema (os, makedirs, glob)

In [ ]:
from os import makedirs
import os
import glob
from os import listdir

import dotenv
def load_dotenv():
    """Load the .env file normally and also from the current directory."""
    dotenv.load_dotenv()
    dotenv.load_dotenv(dotenv.find_dotenv(usecwd=True))

load_dotenv()

False

## Básicos (numpy, math, display, locale, time, random, re)

In [218]:
# !python -m pip install jupyter


# !python -m pip install IPython
from IPython.display import display

import math

# !python -m pip install numpy
import numpy as np

import locale
# locale.setlocale(locale.LC_ALL, "pt_BR.UTF-8")  # Use "" for auto, or force e.g. to "en_US.UTF-8"

import time
from datetime import datetime, timedelta, date

from pandas.tseries.offsets import BDay # para os dias úteis
# today = datetime.datetime.today()
# print(today - BDay(4)) # 4 dias úteis atrás

# # !python -m pip install random
import random
random.seed(42)

# !python -m pip install regex
import re

## Leitura e análise de dados (Excel, Pandas, Spark)

In [219]:
# !python -m pip install findspark

# !python -m pip install openpyxl
# import openpyxl

# !python -m pip install xlsxwriter
# import xlsxwriter

# !python -m pip install xlrd
# import xlrd

# !python -m pip install python-calamine
# import python_calamine


# !python -m pip install pandas
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
# pd.set_option('display.float_format', lambda x: '%.2f' % x)

## Finanças (yfinance, mplfinance)

In [220]:
# https://pypi.org/project/yfinance/
# https://github.com/ranaroussi/yfinance/wiki/Ticker

# !python -m pip install yfinance
import yfinance as yf

# !python -m pip install mplfinance
# import mplfinance as mpf

# # Em R
# # https://cran.r-project.org/web/packages/BatchGetSymbols/index.html

# Funções

## _criar_regressao_bd_acao_, _processar_regressao_e_lista_de_indicadores_, _candle_plot_, _plota_candlestick_acha_martelos_

In [ ]:
# https://stackoverflow.com/questions/4383571/importing-files-from-different-folder

import sys
# caution: path[0] is reserved for script path (or '' in REPL)
sys.path.insert(1, os.environ.get('var_caminho_fonte'))

# Refazendo arquivos

## 1. ler_listaB3 e bd_lista_acoes

In [ ]:
# import importlib
# try:
    # importlib.reload(sys.modules['receber_lista_atualizada_tickers'])
# except:
    # pass
# from receber_lista_atualizada_tickers import ler_lista_B3

var_caminho = os.environ.get('var_caminho_fonte')
# var_caminho.split("\\")[-1]
# bd_lista_acoes = ler_lista_B3(var_caminho)

# bd_lista_acoes

In [223]:
# bd_lista_acoes.info()

## 2. tratar_lista_B3 e bd_lista_acoes_tratada

In [ ]:
# bd_lista_acoes_tratada_original = pd.read_excel(var_caminho + '\Bases\Lista de ações Tratada.xlsx')

# # var_coluna_volume = [item for item in bd_lista_acoes_tratada_original.columns if item.startswith("Volume no último dia útil")][0]

# # var_data_ultima_leitura = datetime.strptime(var_coluna_volume.split("lido em")[1].split(")")[0].strip(), "%d/%m/%Y")

# # bd_lista_acoes_tratada_original = bd_lista_acoes_tratada_original.rename(columns = {var_coluna_volume: "Volume no último dia útil"})
# # bd_lista_acoes_tratada_original["Data da leitura (último dia útil)"] = var_data_ultima_leitura

# bd_lista_acoes_tratada_original#.info()

In [ ]:
# import importlib
# try:
    # importlib.reload(sys.modules['receber_lista_atualizada_tickers'])
# except:
    # pass
# from receber_lista_atualizada_tickers import tratar_lista_B3

# # bd_lista_acoes_tratada = tratar_lista_B3(bd_lista_acoes.iloc[:5, :], var_caminho + r"\Bases")
# bd_lista_acoes_tratada = tratar_lista_B3(bd_lista_acoes, var_caminho + r"\Bases")

# bd_lista_acoes_tratada
# # bd_lista_acoes_tratada.info()

In [ ]:
# bd_lista_acoes_tratada_original = pd.read_excel(var_caminho + r'\Bases\Lista de ações Tratada.xlsx')

# bd_lista_acoes_tratada_empilhada = pd.concat([bd_lista_acoes_tratada_original, bd_lista_acoes_tratada]).drop_duplicates(subset = ["Ticker", "Data da leitura (último dia útil)"]) \

# # bd_lista_acoes_tratada_empilhada.to_excel(var_caminho + r'\Bases\Lista de ações Tratada.xlsx', index = False)

# bd_lista_acoes_tratada_empilhada

### Check da base gerada

In [ ]:
# bd_lista_acoes_tratada_empilhada_import = pd.read_excel(var_caminho + r"\Bases\Lista de ações Tratada.xlsx")
# bd_lista_acoes_tratada_empilhada_import

In [ ]:
# bd_lista_acoes_tratada_empilhada_import["Data da leitura (último dia útil)"].unique()

# bd_lista_acoes_tratada_empilhada_import = bd_lista_acoes_tratada_empilhada_import[~(bd_lista_acoes_tratada_empilhada_import["Data da leitura (último dia útil)"].isin(["2025-04-26 14:47:13.250000", "2025-04-26 13:14:47.711000"]))]

# bd_lista_acoes_tratada_empilhada_export = bd_lista_acoes_tratada_empilhada_import.copy()

# bd_lista_acoes_tratada_empilhada_export.to_excel(var_caminho + r'\Bases\Lista de ações Tratada.xlsx', index = False)

In [229]:
# # bd_lista_acoes_tratada_empilhada

# bd_lista_acoes_tratada_empilhada_check = pd.pivot_table(
#     # data = bd_lista_acoes_tratada_empilhada[["Ticker", "Volume no último dia útil", "Data da leitura (último dia útil)"]],
#     data = bd_lista_acoes_tratada_empilhada_import[["Ticker", "Volume no último dia útil", "Data da leitura (último dia útil)"]],
#     index = "Ticker",
#     columns = "Data da leitura (último dia útil)",
#     values = "Volume no último dia útil",
#     aggfunc = "sum"
# )

# bd_lista_acoes_tratada_empilhada_check

# # for coluna in bd_lista_acoes_tratada_empilhada_check.columns:
#     # display(bd_lista_acoes_tratada_empilhada_check[bd_lista_acoes_tratada_empilhada_check[coluna].isna()])

### Check final com as funções já ajustadas

In [ ]:
# import importlib
# try:
    # importlib.reload(sys.modules['receber_lista_atualizada_tickers'])
# except:
    # pass
# from receber_lista_atualizada_tickers import tratar_lista_B3, ler_lista_B3

# bd_lista_acoes_tratada, bd_lista_acoes_tratada_empilhada = tratar_lista_B3(ler_lista_B3(var_caminho + r"\Bases"), var_caminho + r"\Bases")

# # bd_lista_acoes_tratada
# bd_lista_acoes_tratada_empilhada

In [231]:
# bd_lista_acoes_tratada_empilhada = bd_lista_acoes_tratada_empilhada[~(bd_lista_acoes_tratada_empilhada["Data da leitura (último dia útil)"].isin(["2025-04-26 14:58:12.306", "2025-04-26 15:00:00.000", "2025-04-26 15:06:24.698"]))]

In [232]:
# bd_lista_acoes_tratada_empilhada_check = pd.pivot_table(
#     data = bd_lista_acoes_tratada_empilhada[["Ticker", "Volume no último dia útil", "Data da leitura (último dia útil)"]],
#     # data = bd_lista_acoes_tratada_empilhada_import[["Ticker", "Volume no último dia útil", "Data da leitura (último dia útil)"]],
#     index = "Ticker",
#     columns = "Data da leitura (último dia útil)",
#     values = "Volume no último dia útil",
#     aggfunc = "sum"
# )

# bd_lista_acoes_tratada_empilhada_check

In [ ]:
# bd_lista_acoes_tratada_empilhada

# bd_lista_acoes_tratada_empilhada.to_excel(var_caminho + r'\Bases\Lista de ações Tratada.xlsx', index = False)

## 3. detectar_martelos_todos_os_tickers e bd_acoes

In [ ]:
# import importlib
# try:
#     importlib.reload(sys.modules['detectar_martelos'])
# except:
#     pass
# from detectar_martelos import detectar_martelos_todos_os_tickers

# # bd_arquivo_original = pd.read_excel(var_caminho + r"\Bases\Lista de ações Tratada.xlsx").set_index("Ticker")
# # bd_arquivo_original[bd_arquivo_original["Data da leitura (último dia útil)"] == max(bd_arquivo_original["Data da leitura (último dia útil)"])]

# bd_acao_historico, bd_acoes = detectar_martelos_todos_os_tickers()

In [235]:
# bd_acoes.info()

In [ ]:
# bd_acoes_import = pd.read_excel(var_caminho + r"\Bases\Base de Dados Histórico.xlsx",index_col = 0).reset_index()

# bd_acoes_import.info()

In [237]:
# # display(datetime.today())
# display(datetime.now().replace(hour=0, minute=0, second=0, microsecond=0))
# # type(max(bd_acoes_import["Date"]).date())

# display(datetime.now().replace(hour=0, minute=0, second=0, microsecond=0))
# display(max(bd_acoes_import["Date"]).date())

# acao = bd_acoes_import["Ticker"][0]
# yf.Ticker(acao + ".SA").history(
#     # start = max(bd_acoes_import["Date"]).date(),
#     start = datetime.today(),
#     end = datetime.today(),
#     interval = "1d"
# )

In [238]:
# bd_acoes_empilhada = pd.concat([bd_acoes_import, bd_acoes]).drop_duplicates(subset = ["Date", "Ticker"])

# display(bd_acoes_empilhada[bd_acoes_empilhada["Open"].isna()])
# display(bd_acoes_empilhada)

In [239]:
# import importlib
# try:
#     importlib.reload(sys.modules['detectar_martelos'])
# except:
#     pass
# from detectar_martelos import candle_plot

# # var_acao = "HAPV3"
# var_acao = "VAMO3"

# display(bd_acoes_empilhada[bd_acoes_empilhada["Ticker"] == var_acao])

# candle_plot( # Usa o navegador para criar o gráfico interativo
#     bd_acoes_empilhada[bd_acoes_empilhada["Ticker"] == var_acao].set_index("Date"),
#     volume = True,
#     mav = np.nan,
#     colors = ["orange", "yellow", "blue"],
#     titulo = "",
# )

## 4. detectar_martelos_todos_os_tickers e gerar_arquivo_historico

In [240]:
# import importlib
# try:
#     importlib.reload(sys.modules['detectar_martelos'])
# except:
#     pass
# from detectar_martelos import gerar_arquivo_historico

# gerar_arquivo_historico()

=== MONTANDO BASE DE ANÁLISE ===
1 de 3; CPLE6
2 de 3; COCE5
('single positional indexer is out-of-bounds',)
3 de 3; ALUP4
('single positional indexer is out-of-bounds',)
=== FIM DA GERAÇÃO BASE DE ANÁLISE ===
=== LENDO DADOS DE HISTÓRICO ===
1 de 252; AZUL4
2 de 252; CRFB3
3 de 252; HAPV3
4 de 252; COGN3
5 de 252; B3SA3
6 de 252; ITSA4
7 de 252; PETR4
8 de 252; ITUB4
9 de 252; BEEF3
10 de 252; BBDC4
11 de 252; VALE3
12 de 252; CMIG4
13 de 252; ABEV3
14 de 252; RAIZ4
15 de 252; MGLU3
16 de 252; BBAS3
17 de 252; USIM5
18 de 252; CYRE3
19 de 252; LREN3
20 de 252; CPLE6
21 de 252; PCAR3
22 de 252; GGBR4
23 de 252; CSAN3
24 de 252; CCRO3
25 de 252; POMO4
26 de 252; PRIO3
27 de 252; SUZB3
28 de 252; CVCB3
29 de 252; RENT3
30 de 252; RAIL3
31 de 252; LWSA3
32 de 252; IFCM3
33 de 252; BRFS3
34 de 252; MRVE3
35 de 252; VAMO3
36 de 252; WEGE3
37 de 252; MULT3
38 de 252; PETR3
39 de 252; TIMS3
40 de 252; PETZ3
41 de 252; JBSS3
42 de 252; VBBR3
43 de 252; ELET3
44 de 252; CASH3
45 de 252; MRFG3
46 de 252; SRNA3
47 de 252; BRAP4
48 de 252; BPAC11
49 de 252; GOAU4
50 de 252; EQTL3
51 de 252; ENEV3
52 de 252; ANIM3
53 de 252; ASAI3
54 de 252; MOVI3
55 de 252; KLBN11
56 de 252; CSNA3
57 de 252; RDOR3
58 de 252; AZEV4
59 de 252; CPLE3
60 de 252; NTCO3
61 de 252; RADL3
62 de 252; CXSE3
63 de 252; AZTE3
64 de 252; AURE3
65 de 252; BBDC3
66 de 252; RECV3
67 de 252; CMIN3
68 de 252; GFSA3
69 de 252; ALOS3
70 de 252; BRAV3
71 de 252; HYPE3
72 de 252; VIVT3
73 de 252; AMOB3
74 de 252; ECOR3
75 de 252; YDUQ3
76 de 252; OIBR3
77 de 252; JHSF3
78 de 252; TEND3
79 de 252; GMAT3
80 de 252; ENGI11
81 de 252; SIMH3
82 de 252; UGPA3
83 de 252; VIVA3
84 de 252; SBSP3
85 de 252; STBP3
86 de 252; CEAB3
87 de 252; EMBR3
88 de 252; BBSE3
89 de 252; SLCE3
90 de 252; BRKM5
91 de 252; SMFT3
92 de 252; CBAV3
93 de 252; BHIA3
94 de 252; ONCO3
95 de 252; ISAE4
96 de 252; CURY3
97 de 252; EZTC3
98 de 252; TAEE11
99 de 252; KEPL3
100 de 252; SAPR4
101 de 252; RCSL4
102 de 252; SANB11
103 de 252; RAPT4
104 de 252; FLRY3
105 de 252; TOTS3
106 de 252; AZZA3
107 de 252; GOLL4
108 de 252; SMTO3
109 de 252; HBSA3
110 de 252; ENJU3
111 de 252; SBFG3
112 de 252; AMER3
113 de 252; DIRR3
114 de 252; PMAM3
115 de 252; TTEN3
116 de 252; AZEV3
117 de 252; CAML3
118 de 252; GGPS3
119 de 252; SEER3
120 de 252; GRND3
121 de 252; TUPY3
122 de 252; SAPR11
123 de 252; ELET6
124 de 252; PSSA3
125 de 252; QUAL3
126 de 252; BRSR6
127 de 252; EGIE3
128 de 252; ODPV3
129 de 252; ALPA4
130 de 252; CSMG3
131 de 252; INTB3
132 de 252; DXCO3
133 de 252; ZAMP3
134 de 252; MLAS3
135 de 252; KLBN4
136 de 252; GUAR3
137 de 252; ALUP11
138 de 252; IRBR3
139 de 252; CPFE3
140 de 252; LAVV3
141 de 252; CSED3
142 de 252; EVEN3
143 de 252; BMOB3
144 de 252; TFCO4
145 de 252; LJQQ3
146 de 252; MYPK3
147 de 252; VVEO3
148 de 252; PLPL3
149 de 252; NEOE3
150 de 252; MTRE3
151 de 252; HBOR3
152 de 252; SHUL4
153 de 252; MELK3
154 de 252; MDNE3
155 de 252; MILS3
156 de 252; ABCB4
157 de 252; RANI3
158 de 252; POSI3
159 de 252; ORVR3
160 de 252; MDIA3
161 de 252; JALL3
162 de 252; FIQE3
163 de 252; PTBL3
164 de 252; BPAN4
165 de 252; SOJA3
166 de 252; ITUB3
167 de 252; PGMN3
168 de 252; JSLG3
169 de 252; VULC3
170 de 252; ARML3
171 de 252; POMO3
172 de 252; USIM3
173 de 252; ELMD3
174 de 252; LIGT3
175 de 252; TRIS3
176 de 252; VTRU3
177 de 252; KLBN3
178 de 252; PRNR3
179 de 252; PINE4
180 de 252; SEQL3
181 de 252; WIZC3
182 de 252; MATD3
183 de 252; RNEW4
184 de 252; SYNE3
185 de 252; PFRM3
186 de 252; MEAL3
187 de 252; RCSL3
188 de 252; ESPA3
189 de 252; BRAP3
190 de 252; PNVL3
191 de 252; OPCT3
192 de 252; LEVE3
193 de 252; DESK3
194 de 252; PORT3
195 de 252; TGMA3
196 de 252; CMIG3
197 de 252; LOGG3
198 de 252; FRAS3
199 de 252; AERI3
200 de 252; TCSA3
201 de 252; SAPR3
202 de 252; TAEE4
203 de 252; DASA3
204 de 252; TASA4
205 de 252; BLAU3
206 de 252; FESA4
207 de 252; VITT3
208 de 252; BMGB4
209 de 252; HBRE3
210 de 252; AGRO3
211 de 252; MBLY3
212 de 252; VLID3
213 de 252; INEP3
214 de 252; RNEW3
215 de 252; AGXY3
216 de 252; SANB4
217 de 252; AMAR3
218 de 252; ROMI3
219 de 252; TAEE3
220 de 252; LPSB3
221 de 252; IGTI3
222 de 252; DEXP3
223 de 252; TECN3
224 de 252; INEP4
225 de 252; ALPK3
226 de 252; AALR3
227 de 252; VSTE3
228 de 252; SANB3
229 de 252; RNEW11
230 de 252; CSUD3
231 de 252; ITSA3
232 de 252; AMBP3
233 de 252; DMVF3
234 de 252; ALLD3
235 de 252; OIBR4
236 de 252; EUCA4
237 de 252; PDTC3
238 de 252; ENGI4
239 de 252; UNIP6
240 de 252; TRAD3
241 de 252; GOAU3
242 de 252; ETER3
243 de 252; TPIS3
244 de 252; CAMB3
245 de 252; LVTC3
246 de 252; SCAR3
247 de 252; LUPA3
248 de 252; BIOM3
249 de 252; BOBR4
250 de 252; PTNT4
251 de 252; DEXP4
252 de 252; UCAS3
=== FIM DA LEITURA DOS DADOS DE HISTÓRICO ===

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,HLC,Ticker
0,2025-04-25,2.33,2.40,1.94,1.95,281053900,0.00,0.00,2.10,AZUL4
1,2025-04-25,8.66,8.76,8.53,8.64,65204100,0.00,0.00,8.64,CRFB3
2,2025-04-25,2.44,2.45,2.37,2.41,63722300,0.00,0.00,2.41,HAPV3
3,2025-04-25,2.53,2.56,2.48,2.50,37880500,0.00,0.00,2.51,COGN3
4,2025-04-25,13.11,13.44,13.04,13.39,37600600,0.00,0.00,13.29,B3SA3
...,...,...,...,...,...,...,...,...,...,...
247,2025-04-25,10.00,10.20,9.80,10.14,25700,0.00,0.00,10.05,BIOM3
248,2025-04-25,1.65,1.70,1.63,1.68,25200,0.00,0.00,1.67,BOBR4
249,2025-04-25,6.30,6.36,6.07,6.07,22900,0.00,0.00,6.17,PTNT4
250,2025-04-25,7.79,7.85,7.79,7.81,19200,0.00,0.00,7.82,DEXP4
251,2025-04-25,1.58,1.63,1.58,1.58,18700,0.00,0.00,1.60,UCAS3

In [ ]:
# bd_acoes_import = pd.read_excel(var_caminho + r"\Bases\Base de Dados Histórico.xlsx",index_col = 0).reset_index()

# # bd_acoes_import.info()

# import importlib
# try:
#     importlib.reload(sys.modules['detectar_martelos'])
# except:
#     pass
# from detectar_martelos import candle_plot

# var_acao = "HAPV3"
# # var_acao = "VAMO3"

# # display(bd_acoes_import[bd_acoes_import["Ticker"] == var_acao])

# candle_plot( # Usa o navegador para criar o gráfico interativo
#     bd_acoes_import[bd_acoes_import["Ticker"] == var_acao].set_index("Date"),
#     volume = True,
#     mav = np.nan,
#     colors = ["orange", "yellow", "blue"],
#     titulo = "",
# )

## 5. detectar_martelos_todos_os_tickers e bd_acao_historico

In [ ]:
bd_acoes_import_historico = pd.read_excel(var_caminho + r"\Bases\Base de Dados Histórico.xlsx")
# bd_acoes_import_historico.info()

# acoes = bd_acoes_import_historico["Ticker"].unique()
# acoes
acoes = ["CPLE6"]
# acoes = ["ALUP4"]


qtd_dias_maximo = 55
# bd_acoes_import_historico[bd_acoes_import_historico["Date"] >= (max(bd_acoes_import_historico["Date"]) - timedelta(days=qtd_dias_maximo))]
bd_acao = bd_acoes_import_historico[
    (bd_acoes_import_historico["Ticker"] == acoes[0]) *
    (bd_acoes_import_historico["Date"] >= (max(bd_acoes_import_historico["Date"]) - timedelta(days=qtd_dias_maximo)))
].set_index("Date")
bd_acao = bd_acao.select_dtypes(exclude=['object']).interpolate()
bd_acao["Ticker"] = acoes[0]
bd_acao
# bd_acao.info()

,Open,High,Low,Close,Volume,Dividends,Stock Splits,HLC,Ticker
Date,,,,,,,,,
2025-03-05,9.56,9.67,9.40,9.62,15652700,0.00,0.00,9.56,CPLE6
2025-03-06,9.62,9.70,9.52,9.59,14742300,0.00,0.00,9.60,CPLE6
2025-03-07,9.53,9.79,9.44,9.75,16106300,0.00,0.00,9.66,CPLE6
2025-03-10,9.75,9.81,9.64,9.70,15112800,0.00,0.00,9.71,CPLE6
2025-03-11,9.65,9.72,9.54,9.70,12607200,0.00,0.00,9.65,CPLE6
2025-03-12,9.69,9.83,9.68,9.74,11700000,0.00,0.00,9.75,CPLE6
2025-03-13,9.74,9.98,9.65,9.91,10331500,0.00,0.00,9.85,CPLE6
2025-03-14,9.97,10.25,9.90,10.15,16997000,0.00,0.00,10.10,CPLE6
2025-03-17,10.13,10.28,10.08,10.21,13268600,0.00,0.00,10.19,CPLE6
2025-03-18,10.21,10.32,10.17,10.23,8757400,0.00,0.00,10.24,CPLE6
2025-03-19,10.27,10.51,10.24,10.41,16108200,0.00,0.00,10.39,CPLE6
2025-03-20,10.41,10.47,10.28,10.32,7681900,0.00,0.00,10.36,CPLE6
2025-03-21,10.33,10.40,10.24,10.28,17173200,0.00,0.00,10.30,CPLE6
2025-03-24,10.23,10.44,10.19,10.25,19477000,0.00,0.00,10.29,CPLE6
2025-03-25,10.26,10.42,10.24,10.31,9484800,0.00,0.00,10.32,CPLE6
2025-03-26,10.37,10.43,10.29,10.38,9953300,0.00,0.00,10.36,CPLE6
2025-03-27,10.38,10.51,10.31,10.35,12639600,0.00,0.00,10.39,CPLE6
2025-03-28,10.31,10.36,10.22,10.30,7695500,0.00,0.00,10.29,CPLE6
2025-03-31,10.29,10.38,10.23,10.23,10842500,0.00,0.00,10.28,CPLE6
2025-04-01,10.35,10.46,10.23,10.37,15245400,0.00,0.00,10.35,CPLE6
2025-04-02,10.34,10.46,10.29,10.38,10034300,0.00,0.00,10.37,CPLE6
2025-04-03,10.36,10.78,10.36,10.64,18535700,0.00,0.00,10.59,CPLE6
2025-04-04,10.56,10.62,10.34,10.44,20161700,0.00,0.00,10.47,CPLE6
2025-04-07,10.35,10.59,10.23,10.35,23823400,0.00,0.00,10.39,CPLE6
2025-04-08,10.38,10.53,10.26,10.29,23991100,0.00,0.00,10.36,CPLE6
2025-04-09,10.22,10.63,10.14,10.45,26298200,0.00,0.00,10.41,CPLE6
2025-04-10,10.34,10.50,10.31,10.44,12650200,0.00,0.00,10.42,CPLE6
2025-04-11,10.49,10.57,10.34,10.49,12342000,0.00,0.00,10.47,CPLE6
2025-04-14,10.61,10.75,10.48,10.74,10859000,0.00,0.00,10.66,CPLE6
2025-04-15,10.70,10.84,10.66,10.71,11832200,0.00,0.00,10.74,CPLE6
2025-04-16,10.61,10.78,10.61,10.66,9209100,0.00,0.00,10.68,CPLE6
2025-04-17,10.62,10.83,10.59,10.83,10075900,0.00,0.00,10.75,CPLE6
2025-04-22,10.83,11.06,10.76,10.96,19981900,0.00,0.00,10.93,CPLE6
2025-04-23,11.02,11.17,10.99,11.06,17160800,0.00,0.00,11.07,CPLE6
2025-04-24,11.11,11.46,11.11,11.43,18644800,0.00,0.00,11.33,CPLE6
2025-04-25,11.11,11.46,11.11,11.43,0,0.20,0.00,11.33,CPLE6

In [ ]:
bd_arquivo_original = pd.read_excel(var_caminho + r"\Bases\Lista de ações Tratada.xlsx").set_index("Ticker")
bd_arquivo_original = bd_arquivo_original[bd_arquivo_original["Data da leitura (último dia útil)"] == max(bd_arquivo_original["Data da leitura (último dia útil)"])]

acao = acoes[0]
display(len(bd_arquivo_original.reset_index().columns.to_list()))
display(len([acao] + bd_arquivo_original.loc[acao].to_list()))

63

63

In [251]:
import importlib
try:
    importlib.reload(sys.modules['detectar_martelos'])
except:
    pass
from detectar_martelos import processar_regressao_e_lista_de_indicadores

lista_regressao_e_indicadores_cabecalho_maximo, lista_regressao_e_indicadores_maximo = processar_regressao_e_lista_de_indicadores(
    bd_acao.iloc[-(qtd_dias_maximo):].copy(),
    "HLC",
    qtd_dias_maximo
)

# display(lista_regressao_e_indicadores_cabecalho_maximo)
# display(lista_regressao_e_indicadores_maximo)

# criar_regressao_bd_acao(
#     bd_acao,
#     coluna = "Close",
#     print_variaveis = False,
#     plot_grafico = False,
#     tamanho_figsize = (10,5),
#     rotacao = 45,
#     titulo = "Pontos no fechamento da ação",
#     var_pular_final_de_semana_feriados = False,
# ):

=== MONTANDO BASE DE ANÁLISE ===
1 de 2; COCE5
('COCE5',)
2 de 2; ALUP4
('ALUP4',)
=== FIM DA GERAÇÃO BASE DE ANÁLISE ===

In [ ]:
import importlib
try:
    importlib.reload(sys.modules['detectar_martelos'])
except:
    pass
from detectar_martelos import detectar_martelos_todos_os_tickers

detectar_martelos_todos_os_tickers()

# bd_arquivo_original = pd.read_excel(var_caminho + r"\Bases\Lista de ações Tratada.xlsx").set_index("Ticker")
# bd_arquivo_original = bd_arquivo_original[bd_arquivo_original["Data da leitura (último dia útil)"] == max(bd_arquivo_original["Data da leitura (último dia útil)"])]

# bd_arquivo_original.loc["CPLE6"]

=== MONTANDO BASE DE ANÁLISE ===
1 de 8; COCE5
('COCE5',)
2 de 8; ALUP4
('ALUP4',)
3 de 8; HAPV3
4 de 8; AZUL4
5 de 8; COGN3
6 de 8; PETR4
7 de 8; B3SA3
8 de 8; USIM5
=== FIM DA GERAÇÃO BASE DE ANÁLISE ===
=== MONTANDO BASE DE ANÁLISE ===
1 de 8; COCE5
('COCE5',)
2 de 8; ALUP4
('ALUP4',)
3 de 8; HAPV3
4 de 8; AZUL4
5 de 8; COGN3
6 de 8; PETR4
7 de 8; B3SA3
8 de 8; USIM5
=== FIM DA GERAÇÃO BASE DE ANÁLISE ===

,Ticker,Nome da Empresa,Volume no último dia útil,Data da leitura (último dia útil),industry,sector,fullTimeEmployees,dividendRate,dividendYield,exDividendDate,...,2025-04-24; Low,2025-04-24; Close,2025-04-24; Volume,2025-04-24; Dividends,2025-04-24; Stock Splits,2025-04-24; HLC,Alfa HLC; últimos 13 dias,Alfa HLC; últimos 55 dias,Martelos,Tipos de Martelos
0,HAPV3,Hapvida,64731600,2025-04-26,Insurance - Life,Financial Services,NaN,NaN,NaN,"1,640,649,600.00",...,2.23,2.44,177762600,0.00,0.00,2.39,0.02,0.00,"2025-03-11, 2025-03-13, 2025-03-26, 2025-04-01...","Subida, Subida, Subida, Subida, Subida, Subida..."
1,AZUL4,Azul,282174900,2025-04-26,Airlines,Industrials,"15,367.00",NaN,NaN,NaN,...,2.35,2.36,153518000,0.00,0.00,2.62,-0.04,-0.03,"2025-03-05, 2025-03-10, 2025-03-12, 2025-03-19...","Descida, Descida, Descida, Subida, Descida, Su..."
2,COGN3,Cogna,37935400,2025-04-26,Education & Training Services,Consumer Defensive,"24,187.00",0.26,10.48,"1,745,884,800.00",...,2.37,2.52,67304100,0.00,0.00,2.49,0.04,0.03,"2025-03-06, 2025-03-17, 2025-03-20, 2025-03-21...","Subida, Subida, Subida, Subida, Subida, Subida..."
3,PETR4,Petrobras,35579100,2025-04-26,Oil & Gas Integrated,Energy,"41,778.00",7.11,23.31,"1,744,848,000.00",...,30.06,30.43,61589200,0.00,0.00,30.44,-0.15,-0.13,"2025-03-10, 2025-03-12, 2025-03-18, 2025-03-20...","Subida, Descida, Subida, Subida, Subida, Subid..."
4,B3SA3,B3,37609700,2025-04-26,Financial Data & Stock Exchanges,Financial Services,NaN,0.25,1.88,"1,742,947,200.00",...,12.68,13.27,57242400,0.00,0.00,13.08,0.10,0.05,"2025-03-21, 2025-03-26, 2025-03-27, 2025-03-28...","Subida, Descida, Descida, Descida, Subida, Sub..."
5,USIM5,Usiminas,17748600,2025-04-26,Steel,Basic Materials,NaN,0.28,4.87,"1,714,089,600.00",...,5.67,5.81,48473400,0.00,0.00,5.91,0.06,-0.01,"2025-03-10, 2025-03-12, 2025-03-17, 2025-03-18...","Subida, Subida, Subida, Descida, Subida, Subid..."